# database
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mysite?autoReconnect=true&useSSL=false&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: mysql
    password: 123123
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    #设置热部署
    #开启热部署
    devtools:
      restart:
        enabled: true
    #重启范围
    additional-paths: src/main/java

  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/views/

# 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath*:/com/xiaobowd/mysite/mapper/*Mapper.xml
  type-aliases-package: com.xiaobowd.mysite.bean
  table:
    auto: update
  model:
    pack: com.xiaobowd.mysite.bean
  database:
    type: mysql
  #开启驼峰映射
  configuration:
    map-underscore-to-camel-case: true
#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql