package com.xiaobowd.mysite.mapper;

import com.xiaobowd.mysite.bean.AlipayTransactionRecordVO;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
@Repository
public interface AlipayTransactionRecordVOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ALIPAY_TRANSACTION_RECORDS
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String transactionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ALIPAY_TRANSACTION_RECORDS
     *
     * @mbggenerated
     */
    int insert(AlipayTransactionRecordVO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ALIPAY_TRANSACTION_RECORDS
     *
     * @mbggenerated
     */
    int insertSelective(AlipayTransactionRecordVO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ALIPAY_TRANSACTION_RECORDS
     *
     * @mbggenerated
     */
    AlipayTransactionRecordVO selectByPrimaryKey(String transactionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ALIPAY_TRANSACTION_RECORDS
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AlipayTransactionRecordVO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ALIPAY_TRANSACTION_RECORDS
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AlipayTransactionRecordVO record);

    int insertBatch(List<AlipayTransactionRecordVO> recordVOS);
}